spring:
  datasource:
    url: jdbc:mysql://10.10.10.101:3306/honeyrock?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: honeyrock
    password: 12345678
    
  thymeleaf:
    cache: false

  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"
      
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml